package cn.cpst.rit.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import cn.cpst.rit.model.Mail;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "MailCsService_GnPortType", targetNamespace = "http://service.rit.cpst.cn")
public interface MailCsServiceGnPortType {

	/**
	 * 
	 * @param in2
	 * @param in1
	 * @param in0
	 * @return returns cn.cpst.rit.model.Mail
	 */
	@WebMethod
	@WebResult(name = "out", targetNamespace = "http://service.rit.cpst.cn")
	@RequestWrapper(localName = "getMails", targetNamespace = "http://service.rit.cpst.cn", className = "cn.cpst.rit.service.GetMails")
	@ResponseWrapper(localName = "getMailsResponse", targetNamespace = "http://service.rit.cpst.cn", className = "cn.cpst.rit.service.GetMailsResponse")
	public Mail getMails(
			@WebParam(name = "in0", targetNamespace = "http://service.rit.cpst.cn") String in0,
			@WebParam(name = "in1", targetNamespace = "http://service.rit.cpst.cn") String in1,
			@WebParam(name = "in2", targetNamespace = "http://service.rit.cpst.cn") String in2);

}
